### ISSUE TITLE
returned flounder instance is an array if target is jQuery wrapped

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/flounder#98]
### current

when passing just one target, the returned flounder object instance is either an array (flounder object beeing the only array element) if the target is jQuery wrapped **or** an object (flounder) if the target is the DOM element. 
![screen shot 2016-06-24 at 16 43 23](https://cloud.githubusercontent.com/assets/6839359/16340912/cba6d390-3a2a-11e6-861f-151e966eb86b.png)

I see the reasoning for returning an array in case of multiple targets. But what do you think of returning the flounder object (not wrapped in an array) in both cases ?

### wanted 

exclude `instanceof JQuery` targets from this closure (as jQuery wrapped elements have length of `1`):
https://github.com/sociomantic-tsunami/flounder/blob/master/src/core/flounder.js#L80
in order to always return the flounder object (not wrapped in an array) for single targets. 

Why? as it's not expected from the docs that the supported target options (https://github.com/sociomantic-tsunami/flounder#target-options) lead to different types beeing returned and in order to not have to access the flounder object with `$($0).flounder[ 0 ].` when accessing api methods in case of jQuery targets.

**Comment by mousemke** [comment]
you've just created flounder 1.0.0 ^^

**Comment by mousemke** [comment]
so.  after discussion around the office here, we've come to an answer.

$ and µ flounder will always return $ and µ objects, however any other flounder will only return a single element.  Expected behavior is 1 element since you would never expect `new` to _not_ return an instance of the class.  if there is more than 1 element fed into it (or found in the case of queries) flounder will only take the first one and issue a console warning that the other element(s) was dropped.

That said, in your use case, you may want to consider using the $ wrapper
